# UNIVERSIDADE FEDERAL DE UBERLÂNDIA

# Dinâmica de Rotores

Aluno:
    
    Cristofer Antoni Souza Costa
    
Professor:

    Aldemir Cavallini Jr.

# Sumário

- [Introdução](#Introdução)

- [Importando bibliotecas e efetuando configurações](#Importando-bibliotecas-e-efetuando-configurações)

- [Características do Conjunto Rotativo](#Características-do-Conjunto-Rotativo)

    - [Sistema de coordenadas](#Sistema-de-coordenadas)

    - [Disco](#Disco)

    - [Eixo](#Eixo)



# Introdução

O objetivo desse trabalho consiste em caracterizar o comportamento dinâmico de um sistema formado por um conjunto rotativo submetido a torção e flexão. O conjunto rotativo é composto por um eixo e disco (desbalanceado), suportado por um par de mancais.  Deseja-se prever os seguintes aspectos ainda em etapa de projeto:
1. Torque nominal:
	- Determinação do mínimo diâmetro do eixo.
2. Torção:
	- Comportamento estático e dinamico.
    - Velocidades críticas quanto ao comportamento vibracional torcional.
	- Comportamento em transientes de partida e parada do equipamento.
3. Flexão:
    - Coportamento dinâmico;
	- Velocidades críticas quanto ao comportamento vibracional lateral.
	- Possíveis instabilidades.
	- Resposta à aplicação de massa de desbalanço.
	- Resposta a forças assíncronas.

# Importando bibliotecas e efetuando configurações

In [3]:
import numpy as np
import plotly.graph_objects as go
from pint import UnitRegistry
from plot_vectors import plot_vectors

# Configuring Pint
ureg = UnitRegistry()
Q_ = ureg.Quantity

# Características do Conjunto Rotativo

Os elementos básicos que compôe o conjunto rotativo são: o disco; o eixo; os mancais; e os elementos de selagem. Visto que em aplicações reais, o desblancemento não pode ser completamente eliminado, massas de desbalanceamento também estão presente na modelagem.

Procedimento de modelagem:

1. Determinar expressões para a energia cinética do disco, do eixo e das massas de dos balanços.

2. Determinar expressões para a energia de deformação, com intuito de caracterizar o eixo.

3. Forças para caracterizar mancais e selagens são utilizadas para determinar o trabalho virtual.

## Sistema de Referência

Buscando compreender os fenômenos relacionados com os movimentos descritos pelo conjunto rotativo, o sistema será representado matematicamente com o auxílio de dois sistemas de referência. Um inercial $R_0(X-Y-Z)$ e outro móvel $R(x-y-z)$.

<div>
<img src="img/Coordinate_system.png" width="400"/>
</div>

Toda a representação matemática é baseada em cursores considerando uma origem predefinida. Coforme descrito a seguir.

- **Sistema inercial**, composto pela origem $O$ e cursores $\hat{X}$, $\hat{Y}$, $\hat{Z}$, na forma<br><br>
$$R_0:\{O, \hat{X}, \hat{Y}, \hat{Z}\}.$$<br>
Sua origem coincide com o centro geométrico dos mancais, e nesta base os vetores serão representados a partir dos cursores $\hat{X}$, $\hat{Y}$, $\hat{Z}$. Por exemplo, o vetor posição pode ser expresso como<br><br>
$$\textbf{r}_{R_0} = X_0 \hat{X} + Y_0 \hat{Y} + Z_0 \hat{Z}.$$<br>
As grandezas escalares $X_0$, $Y_0$, e  $Z_0$ indicam a amplitude deste vetor nas respectivas direções.

<br>

- **Sitema móvel**, composto pela origem $G$ e cursores $\hat{x}$, $\hat{y}$, $\hat{z}$, na forma<br><br>
$$R:\{G, \hat{x}, \hat{y}, \hat{z}\}.$$<br>
Sua origem coincide com o centro de massa do disco, e nesta base os vetores serão representados a partir dos cursores, por exemplo, o vetor posição pode ser expresso como<br><br>
$$\textbf{r}_{R} = \textit{x} \hat{x} + \textit{y} \hat{y} + \textit{z} \hat{z}.$$<br>
E, de forma análoga ao utilizado no sistema inercial, as grandezas escalares $x$, $y$ e $z$ indicam a amplitude deste vetor nas respectivas direções.

### Transfomação de Coordenadas

O fato de o sistema de coordenadas móvel girar, implica que os sistemas móvel $R(x-y-z)$ e o sistema inercial $R_0(X-Y-Z)$ passam a guardar uma relação entre seus cursores dada por meio dos angulos $\psi=\psi(t)$, $\theta=\theta(t)$ e $\phi=\phi(t)$ conforme figura abaixo. Esta relação entre sistemas é dada pela matriz de transformação de coordenadas.

<div>
<img src="img/Coordinate_system_ complete.png" width="500"/>
</div>

Para coincidir a orientação do sistema de referência móvel com o sistema inercial, primeiramente o sistema inercial é rotacionado no sentido positivo, de acordo com a regra da mão direitra, com o angulo $\psi$ em torno do eixo $Z$. Assim sendo podemos escrever o vetor de velocidade angular:

$$\bf{\omega}_{R_0} = 
\begin{align}
    \begin{Bmatrix}
        0 \\
        0 \\
        \dot{\psi}(t)
    \end{Bmatrix}
\end{align}
$$

Projetando-se os cursores da base móvel sobre a base inercial, chega-se a seguinte relação entre eles, escrita de forma matricial

$$\begin{align}
    \begin{Bmatrix}
        x_1 \\
        y_1 \\
        z_1
    \end{Bmatrix}_{R_1}
\end{align}
=
\begin{bmatrix}
    \cos{\psi} & \sin{\psi} & 0 \\ 
    -\sin{\psi} & \cos{\psi} & 0 \\ 
    0 & 0 & 1
\end{bmatrix}
\begin{Bmatrix}
    X_0 \\
    Y_0 \\
    Z_0
\end{Bmatrix}_{R_0},
$$

onde 

$${}_{R_1}T_{R_0} = 
\begin{bmatrix}
    \cos{\psi} & \sin{\psi} & 0 \\ 
    -\sin{\psi} & \cos{\psi} & 0 \\ 
    0 & 0 & 1
\end{bmatrix}$$

é a matriz de transformação de coordenadas que, quando aplicada a um vetor representado no sistema $R_0$, gera um representação no sistema de referência intermediário $R_1 : \{G, x_1, y_1, z_1\}$.

Assim sendo, qualquer vetor descrito no sistema $R_0$ ou $R_1$ pode ser reescrito em outro sistema $R_1$ ou $R_0$ simplesmente quando os mesmos são multiplicados pela matriz de transformação de coordenadas ${}_{R_1}T_{R_0}$ ou ${}_{R_1}T^{-1}_{R_0}$. 

Destaca-se aqui que as matrizes de transformação de coordenadas são conceituadas em Álgebra Linear como transformação linear. Ou seja, são matrizes ortogonais e, logo, são quadradas e sua inversa é igual a sua transposta, 

$${}_{R_1}T_{R_0}^{-1} = {}_{R_1}T_{R_0}^T = {}_{R_0}T_{R_1},$$

e seu determinante -e igual a um,

$$\det{({}_{R_1}T_{R_0})} = 1.$$

Assim sendo, temos

$$\textbf{r}_{R_1} = {}_{R_1}T_{R_0} \cdot \textbf{r}_{R_0} \\
\textbf{r}_{R_0} = {}_{R_1}T_{R_0}^T \cdot \textbf{r}_{R_1}$$

ou seja, a transformação linear representada pela matriz ${}_{R_1}T_{R_0}^T$ atuaria na transformação de coordenadas do sistema sistema móvel $R_1$ para o sistema inercial $R_0$.

Por exemplo, considerando-se um ângulo $\psi =\pi / 4$, se tivermos o vetor 

$$\textbf{a}_{R_0} = 
\begin{align}
    \begin{Bmatrix}
        0 \\
        1 \\
        0
    \end{Bmatrix}
\end{align}
$$

representado na base $R_0$, aplicando-se a matriz de transformação ${}_{R_1}T_{R_0}$ neste vetor, podemos obteremos sua representação na base $R_1 : \{O, x_1, y_1, Z\}$, na forma
 
$$\textbf{a}_{R_1} = 
\begin{align}
    \begin{Bmatrix}
        \frac{\sqrt{2}}{2} \\
        \frac{\sqrt{2}}{2} \\
        0
    \end{Bmatrix}
\end{align}
$$

O código a seguir ilustra essas transformações e suas propriedades:

In [4]:
# Giro em torno de Z
psi = np.pi / 4

# Matriz de Transformação de Coordenadas R0_R1
transformation_R0_R1 = np.array(([np.cos(psi), np.sin(psi),0],
                                 [-np.sin(psi), np.cos(psi), 0],
                                 [0, 0, 1]))

# Verificando a implementação, definindo um vetor em R0
vector_R0 = np.array(([0, 1, 0]))

# Aplicando a matriz de transformação
vector_R1 = transformation_R0_R1 @ vector_R0
vector_R1

array([0.70710678, 0.70710678, 0.        ])

In [5]:
# o módulo do vector_R0 é igual ao vector_R1?
np.linalg.norm(vector_R0) == np.linalg.norm(vector_R1) == 1.0

True

In [6]:
# E voltando para o espaço vetorial R1 para R0
transformation_R0_R1.transpose() @ vector_R1

array([4.26642159e-17, 1.00000000e+00, 0.00000000e+00])

In [7]:
# Matriz de transformação R0_R1
transformation_R0_R1

array([[ 0.70710678,  0.70710678,  0.        ],
       [-0.70710678,  0.70710678,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

In [8]:
# Matriz inversa da matriz de transformação R0_R1
np.linalg.inv(transformation_R0_R1)

array([[ 0.70710678, -0.70710678,  0.        ],
       [ 0.70710678,  0.70710678,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

In [9]:
# Matriz inversa da matriz de transformação R0_R1
transformation_R0_R1.transpose()

array([[ 0.70710678, -0.70710678,  0.        ],
       [ 0.70710678,  0.70710678,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

In [9]:
# Determinante da transformação linear
np.linalg.det(transformation_R0_R1)

1.0

Computando as demais transformações, efetuando rotação nos eixos $x_1$ e $y$, temos:


, originando um novo eixo $x_1$ e $y_1$ (a partir de $X$ e $Y$); posteriormente a rotação $\theta$ se dá em torno do eixo $x_1$, gerando $z_1$ e $y$ (a partir de $y_1$ e $Z$) e por fim a rotação $\phi$ se dá em torno do eixo $y$, gerando $z$ e $x$ (a partir de $z_1$ e $x_1$).

### Vetor de velocidade angular



In [14]:
# Giro em torno de X
theta = np.pi / 4

# Giro em torno de Y
phi = np.pi / 4

transformation_R2_R1 = np.array(([np.cos(psi), np.sin(psi),0],
                                 [-np.sin(psi), np.cos(psi), 0],
                                 [0, 0, 1]))

transformation_R_R2 = np.array(([np.cos(psi), np.sin(psi),0],
                                [-np.sin(psi), np.cos(psi), 0],
                                [0, 0, 1]))

## Disco

Assume-se que o mesmo é rígido e caracterizado somente por sua energia cinética.

### Energia Cinética

## 





In [ ]:
v1_R0.shape

In [ ]:
A = np.array(([1,2],[1,0]))

In [ ]:
A @ np.array(([1,2]))

In [ ]:
# Plotting

shaft = 30

# Cylinder parameters
offset = 15 # from Y origin
r = 2 # radius
h = 1  # height
theta = np.linspace(0, 2*np.pi, 10)
z = r * np.cos(theta)
x = r * np.sin(theta)

# Create cylinder surface
cylinder = go.Surface(x=np.outer(x, np.ones_like(theta)),
                      y=offset + np.outer(np.ones_like(theta), np.linspace(0, h, 50)),
                      z=np.outer(z, np.ones_like(theta)),
                      colorscale='Viridis',
                      showscale=False)

# Line in origin
bearing_line = go.Scatter3d(x=[0, 0],
                            y=[0, shaft],
                            z=[0, 0],
                            mode='lines',
                            marker={'color': 'green'},
                            line={'dash': 'longdash',
                                  'width': 5})

# Create figure
fig = go.Figure(data=[cylinder, bearing_line])

# Set layout
fig.update_layout(scene=dict(aspectratio=dict(x=1, y=1, z=1),
                             aspectmode='manual'))

# Show plot
fig.show()


In [ ]:
np.identity(4)